# Generated by Django 6.0.8 on 2026-08-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0037_alter_source_fallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='prefer_default_audio',
            field=models.BooleanField(default=False, help_text='Prefer the "default" audio track (for example a dubbed or localised track) over the "original" audio track when both are available', verbose_name='prefer default audio'),
        ),
    ]
